<a href="https://colab.research.google.com/github/narasimha24-05/ml/blob/main/ml2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as ap
one = ap.array([1, 2, 3, 4, 5])
print(one)
print(one.ndim)
print(one.size)
print(one.shape)

[1 2 3 4 5]
1
5
(5,)


In [ ]:
import numpy as ap
two=ap.array([[1,2,3],[4,5,4]])
print(two)
print(two.ndim)
print(two.size)
print(two.shape)

[[1 2 3]
 [4 5 4]]
2
6
(2, 3)


In [ ]:
import numpy as ap
three=ap.array([[1,2,3],[4,5,4],[1,1,1]])
print(three)
print(three.ndim)
print(three.size)
print(three.shape)

[[1 2 3]
 [4 5 4]
 [1 1 1]]
2
9
(3, 3)


In [ ]:
import numpy as np

n = int(input("enter size: "))
array=[]
for i in range(n):
  ele=float(input())
  array.append(ele)

array_mean=np.mean(array)
print(array_mean)

enter size: 5
1.3
2.2
3.4
4.0
5.5
3.28


In [ ]:
import numpy as np

n = int(input("enter size: "))
array=[]
for i in range(n):
  ele=float(input())
  array.append(ele)

array_median=np.median(array)
print("the median is",array_median)

enter size: 5
1
2
3
4
5
the median is 3.0


In [2]:
import numpy as np
from statistics import mean, median, mode
data = [2, 4, 4, 4, 5, 5, 7, 9]
print("Mean:", mean(data))
print("Median:", median(data))
print("Mode:", mode(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))

Mean: 5
Median: 4.5
Mode: 4
Variance: 4.0
Standard Deviation: 2.0


In [9]:
import math
print(math.pow(2, 35))
print(math.sqrt(15))
print(math.exp(3))
print(math.log(100, 10))

34359738368.0
3.872983346207417
20.085536923187668
2.0


In [6]:
print(math.sin(math.pi/2))
print(math.cos(0))
print(math.tan(math.pi/4))

print(math.radians(90))

print(math.degrees(math.pi))

1.0
1.0
0.9999999999999999
1.5707963267948966
180.0


In [10]:
print(math.factorial(6))
print(math.gcd(23, 8))
print(math.fabs(-7.5))

720
1
7.5


In [8]:
print(math.pi)
print(math.e)

3.141592653589793
2.718281828459045
