<a href="https://colab.research.google.com/github/narasimha24-05/ml/blob/main/ml2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as ap
one = ap.array([1, 2, 3, 4, 5])
print(one)
print(one.ndim)
print(one.size)
print(one.shape)

[1 2 3 4 5]
1
5
(5,)


In [28]:
import numpy as ap
two=ap.array([[1,2,3],[4,5,4]])
print(two)
print(two.ndim)
print(two.size)
print(two.shape)

[[1 2 3]
 [4 5 4]]
2
6
(2, 3)


In [27]:
import numpy as ap
three=ap.array([[1,2,3],[4,5,4],[1,1,1]])
print(three)
print(three.ndim)
print(three.size)
print(three.shape)

[[1 2 3]
 [4 5 4]
 [1 1 1]]
2
9
(3, 3)


In [17]:
import numpy as np

n = int(input("enter size: "))
array=[]
for i in range(n):
  ele=float(input())
  array.append(ele)

array_mean=np.mean(array)
print(array_mean)

enter size: 5
1.3
2.2
3.4
4.0
5.5
3.28


In [21]:
import numpy as np

n = int(input("enter size: "))
array=[]
for i in range(n):
  ele=float(input())
  array.append(ele)

array_median=np.median(array)
print("the median is",array_median)

enter size: 5
1
2
3
4
5
the median is 3.0
